### ISSUE TITLE
Add support for running without writing code

### ISSUE THREAD

**Issue by billonahill** [JudeScarbrough/ModelNode#1]
Instead of requiring the user to write code like `examples/py_run_server.py` it would be cool if you could run the server just by creating a config file and running a start command from the cli. For example the gettting started docs could be to create `config.yaml`:
```
routes:
  - path: /llama
     model: llama3.2
  - path: /deepseek
     model: deepseek-r1:latest
}
```

Then start the server:
```
python -m nodemodel --config config.yaml --port 8080
```
The argparse library can be used to parse command line args and the pyaml library for parsing yaml configs.

Ultimately you could even package nodemodel into a wheel that could be installed with pip with [project.scripts](https://medium.com/@jonathan_b/building-a-python-wheel-with-pyproject-toml-bbab842e989a) so you could do something like this:
```
$ nodemodel --config config.yaml --port 8080
```
